export default {
    // own ones
    '_mail_required': 'Email address is required.',
    '_password_required': 'Password is required.',
    '_password_match': 'Passwords need to match.',

    // supabase ones
    'anonymous_provider_disabled': 'Anonymous sign-ins are disabled.',
    'bad_code_verifier': 'bad_code_verifier',
    'bad_json': 'bad_json',
    'bad_jwt': 'bad_jwt',
    'bad_oauth_callback': 'bad_oauth_callback',
    'bad_oauth_state': 'bad_oauth_state',
    'captcha_failed': 'CAPTCHA challenge could not be verified with the CAPTCHA provider.',
    'conflict': 'General database conflict.',
    'email_address_invalid': 'Email address is not valid.',
    'email_address_not_authorized': 'Email address is not authorized.',
    'email_conflict_identity_not_deletable': 'email_conflict_identity_not_deletable',
    'email_exists': 'Email address already exists in the system.',
    'email_not_confirmed': 'Signing in is not allowed for this user as the email address is not confirmed.',
    'email_provider_disabled': 'Signups are disabled for email and password.',
    'flow_state_expired': 'flow_state_expired',
    'flow_state_not_found': 'flow_state_not_found',
    'hook_payload_invalid_content_type': 'hook_payload_invalid_content_type',
    'hook_payload_over_size_limit': 'hook_payload_over_size_limit',
    'hook_timeout': 'hook_timeout',
    'hook_timeout_after_retry': 'hook_timeout_after_retry',
    'identity_already_exists': 'The identity to which the API relates is already linked to a user.',
    'identity_not_found': 'Identity to which the API call relates does not exist.',
    'insufficient_aal': 'insufficient_aal',
    'invite_not_found': 'Invite is expired or already used.',
    'invalid_credentials': 'Login credentials or grant type not recognized.',
    'manual_linking_disabled': 'manual_linking_disabled',
    'mfa_challenge_expired': 'Responding to an MFA challenge should happen within a fixed time period. Request a new challenge.',
    'mfa_factor_name_conflict': 'MFA factors for a single user should not have the same friendly name.',
    'mfa_factor_not_found': 'MFA factor no longer exists.',
    'mfa_ip_address_mismatch': 'The enrollment process for MFA factors must begin and end with the same IP address.',
    'mfa_phone_enroll_not_enabled': 'Enrollment of MFA Phone factors is disabled.',
    'mfa_phone_verify_not_enabled': 'Login via Phone factors and verification of new Phone factors is disabled.',
    'mfa_totp_enroll_not_enabled': 'Enrollment of MFA TOTP factors is disabled.',
    'mfa_totp_verify_not_enabled': 'Login via TOTP factors and verification of new TOTP factors is disabled.',
    'mfa_verification_failed': 'MFA challenge could not be verified -- wrong TOTP code.',
    'mfa_verification_rejected': 'Further MFA verification is rejected.',
    'mfa_verified_factor_exists': 'Verified phone factor already exists.',
    'mfa_web_authn_enroll_not_enabled': 'Enrollment of MFA Web Authn factors is disabled.',
    'mfa_web_authn_verify_not_enabled': 'Login via WebAuthn factors and verification of new WebAuthn factors is disabled.',
    'no_authorization': 'no_authorization',
    'not_admin': 'not_admin',
    'oauth_provider_not_supported': 'This OAuth provider is not supported.',
    'otp_disabled': 'Sign in with OTPs (magic link, email OTP) is disabled.',
    'otp_expired': 'OTP code for this sign-in has expired.',
    'over_email_send_rate_limit': 'Too many emails have been sent to this email address.',
    'over_request_rate_limit': 'Too many requests have been sent.',
    'over_sms_send_rate_limit': 'Too many SMS messages have been sent.',
    'phone_exists': 'Phone number already exists in the system.',
    'phone_not_confirmed': 'Signing in is not allowed as the phone number is not confirmed.',
    'phone_provider_disabled': 'Signups are disabled for phone and password.',
    'provider_disabled': 'OAuth provider is disabled for use.',
    'provider_email_needs_verification': 'provider_email_needs_verification',
    'reauthentication_needed': 'reauthentication_needed',
    'reauthentication_not_valid': 'reauthentication_not_valid',
    'refresh_token_not_found': 'Session containing the refresh token not found.',
    'refresh_token_already_used': 'Refresh token has been revoked.',
    'request_timeout': 'Processing the request took too long.',
    'same_password': 'Using the same password is not allowed.',
    'saml_assertion_no_email': 'saml_assertion_no_email',
    'saml_assertion_no_user_id': 'saml_assertion_no_user_id',
    'saml_entity_id_mismatch': 'saml_entity_id_mismatch',
    'saml_idp_already_exists': 'saml_idp_already_exists',
    'saml_idp_not_found': 'saml_idp_not_found',
    'saml_metadata_fetch_failed': 'saml_metadata_fetch_failed',
    'saml_provider_disabled': 'saml_provider_disabled',
    'saml_relay_state_expired': 'saml_relay_state_expired',
    'saml_relay_state_not_found': 'saml_relay_state_not_found',
    'session_expired': 'The session has expired.',
    'session_not_found': 'The session no longer exists.',
    'signup_disabled': 'Sign ups (new account creation) are disabled on the server.',
    'single_identity_not_deletable': 'Deleting this identity is not allowed.',
    'sms_send_failed': 'Sending an SMS message failed.',
    'sso_domain_already_exists': 'sso_domain_already_exists',
    'sso_provider_not_found': 'sso_provider_not_found',
    'too_many_enrolled_mfa_factors': 'There are already too many enrolled MFA factors.',
    'unexpected_audience': 'unexpected_audience',
    'unexpected_failure': 'Auth service is degraded or a bug is present, without a specific reason.',
    'user_already_exists': 'User with this information (email address, phone number) cannot be created again as it already exists.',
    'user_banned': 'User is banned.',
    'user_not_found': 'User no longer exists',
    'user_sso_managed': 'user_sso_managed',
    'validation_failed': 'Provided parameters are not in the expected format.',
    'weak_password': 'Password doesn\'t meet the password strength criteria.',
}
